### PR TITLE
added error boundaries for catching errors

### PR DESCRIPTION
**Pull request by Simon-157**

### CODE REVIEW

**Review by faddalibrahim — CHANGES_REQUESTED** [review]
wrap the ErrorBoundary around `<App/>` component instead, in the index.js

**Comment by Simon-157** [comment]
> wrap the ErrorBoundary around `<App/>` component instead, in the index.js

It is wrapped in the App component

**Comment by Simon-157** [comment]
> > wrap the ErrorBoundary around `<App/>` component instead, in the index.js
> 
> It is wrapped in the App component

I dont know if that is what is showing at your end, I changed that before commit

**Comment by faddalibrahim** [comment]
now you have wrapped it twice. inside of both index.js and App.js

remove the one in the App.js

**Review by faddalibrahim — APPROVED** [review]

**Pull request merged**
