### PR TITLE
Simon issue 17 error404 for non existent routes

### PR DESCRIPTION
**Pull request by Simon-157**
Created a pull request for the nonexistent route page handler

### CODE REVIEW

**Review by faddalibrahim — CHANGES_REQUESTED** [review]
I can see you are using styled-components to style the PageNotFound

Although style components will scope our styles, we will be using **css modules** instead for this project

here is a quick overview (https://programmingwithmosh.com/react/css-modules-react/)

changes to make
- [ ] replace styled components with **css modules** styling
- [ ] make the folder name small letters **error404**

**Comment by Simon-157** [comment]
> I can see you are using styled-components to style the PageNotFound
> 
> Although style components will scope our styles, we will be using **css modules** instead for this project
> 
> here is a quick overview (https://programmingwithmosh.com/react/css-modules-react/)
> 
> changes to make
> 
> * [ ]  replace styled components with **css modules** styling
> * [ ]  make the folder name small letters **error404**

**Comment by Simon-157** [comment]
Oh okay sure, i didn’t know we are using the normal css. I will do the necessary changes

**Review by faddalibrahim — APPROVED** [review]

**Review by faddalibrahim — CHANGES_REQUESTED** [review]
I just realized the PR was made against the main branch

close this PR and make a new one against **development**

**Pull request closed without merging**
